### ISSUE TITLE
master_node to name mapping isn't working

### ISSUE THREAD

**Issue by bsteph** [untergeek/es_stats_zabbix#1]
When I run: 
/usr/local/bin/es_stats_zabbix --debug --configuration /etc/zabbix/es_stats_zabbix.ini single clusterstate[master_node]

It errors out with the nodeid of the master_node (listed below):

Traceback (most recent call last):
  File "/usr/local/bin/es_stats_zabbix", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.4/site-packages/es_stats_zabbix/es_stats_zabbix.py", line 173, in main
    cli(obj={})
  File "/usr/local/lib/python3.4/site-packages/click/core.py", line 716, in **call**
    return self.main(_args, *_kwargs)
  File "/usr/local/lib/python3.4/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.4/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.4/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, *_ctx.params)
  File "/usr/local/lib/python3.4/site-packages/click/core.py", line 534, in invoke
    return callback(_args, *_kwargs)
  File "/usr/local/lib/python3.4/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, *_kwargs)
  File "/usr/local/lib/python3.4/site-packages/es_stats_zabbix/es_stats_zabbix.py", line 117, in single
    result = apiobj.get(ztuple[2], name=ztuple[1])
  File "/usr/local/lib/python3.4/site-packages/es_stats/es_stats.py", line 42, in get
    return get_value(self.state, key)
  File "/usr/local/lib/python3.4/site-packages/es_stats/utils.py", line 23, in get_value
    return eval("dotted." + notation)
  File "<string>", line 1, in <module>
NameError: name 'WLdzrRR_Gag2j2g67ETQ' is not defined

**Comment by untergeek** [comment]
What version of Elasticsearch?  Which version of the elasticsearch python module are you using?

**Comment by mdiorio** [comment]
I am getting the same error after a server reboot.  
NameError: name 'huFBaK6Xp2Q' is not defined

The full node ID is     fTtY3tAEQy-huFBaK6Xp2Q

It appears that the punctuation in the nodeID isn't being handled properly.

Elasticsearch 2.2.0
Elasticsearch python client version 2.3.0
es-stats version 0.1.0

**Comment by untergeek** [comment]
Thanks for the reports, guys.  I'll see what I can do.

**Comment by magistersart** [comment]
With all recent software installed (a freshly built ES cluster) I get
Traceback (most recent call last):
  File "/usr/bin/es_stats_zabbix", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python2.6/site-packages/es_stats_zabbix/es_stats_zabbix.py", li                                                                                                                                                             ne 173, in main
    cli(obj={})
  File "/usr/lib/python2.6/site-packages/click/core.py", line 716, in **call**
    return self.main(_args, *_kwargs)
  File "/usr/lib/python2.6/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.6/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.6/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, *_ctx.params)
  File "/usr/lib/python2.6/site-packages/click/core.py", line 534, in invoke
    return callback(_args, **kwargs)
  File "/usr/lib64/python2.6/contextlib.py", line 34, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib/python2.6/site-packages/click/core.py", line 86, in augment_usa                                                                                                                                                             ge_errors
    yield
  File "/usr/lib/python2.6/site-packages/click/core.py", line 534, in invoke
    return callback(_args, *_kwargs)
  File "/usr/lib/python2.6/site-packages/click/decorators.py", line 17, in new_f                                                                                                                                                             unc
    return f(get_current_context(), _args, *_kwargs)
  File "/usr/lib/python2.6/site-packages/es_stats_zabbix/es_stats_zabbix.py", li                                                                                                                                                             ne 117, in single
    result = apiobj.get(ztuple[2], name=ztuple[1])
  File "/usr/lib/python2.6/site-packages/es_stats/es_stats.py", line 42, in get
    return get_value(self.state, key)
  File "/usr/lib/python2.6/site-packages/es_stats/utils.py", line 23, in get_val                                                                                                                                                             ue
    return eval("dotted." + notation)
  File "<string>", line 1
    dotted.nodes.1OqUlS6DQc-F2-kWqKcsIg.name
                 ^
SyntaxError: invalid syntax

Python 2.6

**Comment by untergeek** [comment]
I'm sorry to keep everyone waiting.  I've been very busy with my normal day job.  I'll see what I can get to work here soon.

**Comment by untergeek** [comment]
This should be fixed by https://github.com/untergeek/es_stats/commit/80166bb0ea516cfede6cb758fe11475ab23dadb2

**Comment by untergeek** [comment]
And you can correct this by upgrading `es_stats` to v0.2.1.  To use pip to do this:

```
(sudo) pip install -U es_stats
```
